### ISSUE TITLE
SentryRRweb common errors

### ISSUE THREAD

**Issue by fangherk** [getsentry/sentry-rrweb#15]
I added the SentryRRWeb integration via 
```javascript
      integrations: [
        new SentryRRWeb({
          checkoutEveryNth: 100,
          checkoutEveryNms: 15 * 60 * 1000,
          maskAllInputs: false,
        }),
      ]
```
However, in Sentry, I see these three types of errors every so often in captured exceptions.
```
TypeError: Unable to get property 'contains' of undefined or null reference
  at isBlocked(/opt/render/project/src/node_modules/rrweb/es/rrweb/src/utils.js:173:1)
  at genAdds(/opt/render/project/src/node_modules/rrweb/es/rrweb/src/record/mutation.js:358:1)
  at n(/opt/render/project/src/node_modules/rrweb/es/rrweb/src/record/mutation.js:381:1)
  at genAdds(/opt/render/project/src/node_modules/rrweb/es/rrweb/src/record/mutation.js:380:1)
  at n(/opt/render/project/src/node_modules/rrweb/es/rrweb/src/record/mutation.js:381:1)
```
```
TypeError: Unable to get property 'value' of undefined or null reference
  at processMutations(/opt/render/project/src/node_modules/rrweb/es/rrweb/src/record/mutation.js:226:1)
```

```
TypeError: null is not an object (evaluating 'e.__sn')
  at getId(/opt/render/project/src/node_modules/rrweb/es/rrweb/src/utils.js:35:1)
  at ? (/opt/render/project/src/node_modules/rrweb/es/rrweb/src/record/mutation.js:223:34)
```

Any suggestions on how to fix/suppress these errors?

**Comment by dcramer** [comment]
@Yuyz0112 I think these are upstream concerns. Not sure easiest way to cross reference, but do you recognize any of that as existing tickets on rrweb itself?

**Comment by Yuyz0112** [comment]
@dcramer I did not get and report of this error in rrweb. I will watch sentry-rrweb repo and check issues here.

**Comment by daidi** [comment]
This problem can be repeated in IE 11

**Comment by bruno-garcia** [comment]
I believe this is resolved in the new Replay SDK. Please note this repository has been superseded and will no longer be updated.

Please check https://github.com/getsentry/sentry-javascript/tree/master/packages/replay#sentry-session-replay instead, we're happy respond to issues, review and merge PRs there.
